apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
    - name: backend-container
      image: systemy-chmurowe-backend:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: DB_HOST
          value: db-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: genz_social
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
      ports:
        - containerPort: 5000
      livenessProbe:
        httpGet:
          path: /stats
          port: 5000
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
